### 1. Register Prince (admin)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Coulibaly",
  "prenom": "Prince",
  "telephone": "+22600000000",
  "email": "prince@koto.app",
  "motDePasse": "password123"
}

###

### 2. Login Prince
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "prince@koto.app",
  "motDePasse": "password123"
}

###

### 3. Créer un groupe
POST http://localhost:8080/api/groupes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcmluY2VAa290by5hcHAiLCJpYXQiOjE3Nzc5MTAxMTcsImV4cCI6MTc3Nzk5NjUxN30.x9kFv4-JnQQdc9wiXWoSYgpzM-zp1PiWzpDF-wIgfq8C_w2LaDO2F1hTNlEbPZsJg2bUxunMTGakFCnkN-KTiQ

{
  "nom": "Tontine Famille Coulibaly",
  "montantCotisation": 10000,
  "devise": "XOF",
  "nombreMembres": 6,
  "dateDebut": "2026-06-01"
}

###

### 4. Mes groupes
GET http://localhost:8080/api/groupes
Authorization: Bearer TOKEN_PRINCE

###

### 5. Détail d'un groupe
GET http://localhost:8080/api/groupes/GROUP_ID
Authorization: Bearer TOKEN_PRINCE

###

### 6. Générer lien d'invitation
GET http://localhost:8080/api/groupes/f78c25e6-85aa-4834-aefe-20f8408f6d47/invite
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcmluY2VAa290by5hcHAiLCJpYXQiOjE3Nzc5MTAxMTcsImV4cCI6MTc3Nzk5NjUxN30.x9kFv4-JnQQdc9wiXWoSYgpzM-zp1PiWzpDF-wIgfq8C_w2LaDO2F1hTNlEbPZsJg2bUxunMTGakFCnkN-KTiQ