ALTER TABLE cycles ADD COLUMN IF NOT EXISTS cree_le TIMESTAMP DEFAULT NOW();
ALTER TABLE paiements ADD COLUMN IF NOT EXISTS cree_le TIMESTAMP DEFAULT NOW();
ALTER TABLE rappels ADD COLUMN IF NOT EXISTS cree_le TIMESTAMP DEFAULT NOW();